### ISSUE TITLE
Fix navigation

### ISSUE THREAD

**Issue by lianmakesthings** [lianmakesthings/kuberoke#8]
The top navigation stopped working.
E.g. the point "Code of Coduct" should lead to the coc page

This works fine on local development but not in production

**Comment by PiMastah** [comment]
Seems whatever renders the production version strips the attribute values from the href and title attributes:

## live
```
<a href="" class="flex items-center">
    
    <p class="text-base font-medium text-gray-500 hover:text-gray-900" title="">
        Code of Conduct
    </p>
</a>
```

## local

```
<a href="/coc/" class="flex items-center">
    
    <p class="text-base font-medium text-gray-500 hover:text-gray-900" title="Code of Conduct">
        Code of Conduct
    </p>
</a>
```

**Comment by mocdaniel** [comment]
How is the website getting deployed atm?

I'm asking because in both, `docker run --rm -it -v $(pwd):/src -p 1313:1313 klakegg/hugo:latest server` (dev mode) and 

``` terminal
docker run --rm -it -v $(pwd):/src -p 1313:1313 klakegg/hugo:latest
python3 -m http.server --directory ./public <PORT>
```

(allegedly 'prod' mode), navigation works just fine for me. So *I* think, it's got to do with deployment specifics.

**Comment by lianmakesthings** [comment]
Yeah, it seems to work fine locally, both within a Docker container and without even in "prod" mode.
The page is currently deployed via Netlify.
It runs the `hugo` command which builds the static site, then puts the `public` folder on Netlify's webserver.

So... while I was investigating this, I noticed that although I set Netlify's Hugo version to `0.109.0`, I hadn't actually rerun the deployment with the newer version. I reran the deployment and voilà, looks like that fixed it 🤦‍♀️ 

@PiMastah found that bug report I believe. Would you mind linking it here for future reference?

**Comment by PiMastah** [comment]
> Would you mind linking it here for future reference?

https://discourse.gohugo.io/t/menu-links-broken-but-only-when-deployed/41033/3
